In [1]:
print("Hello VS Code, Python fonctionne !")

Hello VS Code, Python fonctionne !

In [2]:
!pip install praw pymongo pandas

Collecting praw
  Downloading praw-8.0.0-py3-none-any.whl.metadata (10 kB)
Collecting pymongo
  Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl.metadata (10 kB)
Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: defusedxml==0.7.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (0.7.1)
Collecting prawcore<5,>=4 (from praw)
  Downloading prawcore-4.0.0-py3-none-any.whl.metadata (6.3 kB)
Collecting update-checker<2.0,>=1.0 (from praw)
  Downloading update_checker-1.0.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: websocket-client<2,>=0.54.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (1.8.0)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting requests<3.0,>=2.34.2 (from prawcore<5,>=4->praw)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2025.1.31)
Downloading praw-8.0.0-py3-none-any.whl (198 kB)
Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl (972 kB)
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 972.8/972.8 kB 7.2 MB/s eta 0:00:00
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------  9.7/9.8 MB 55.4 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 28.8 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.3 MB 64.7 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 64.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 31.4 MB/s eta 0:00:00
Downloading prawcore-4.0.0-py3-none-any.whl (19 kB)
Downloading update_checker-1.0.0-py3-none-any.whl (10 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Installing collected packages: update-checker, tzdata, requests, numpy, dnspython, pymongo, prawcore, pandas, praw
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
Successfully installed dnspython-2.8.0 numpy-2.4.6 pandas-3.0.3 praw-8.0.0 prawcore-4.0.0 pymongo-4.17.0 requests-2.34.2 tzdata-2026.2 update-checker-1.0.0

In [1]:
import praw

In [3]:
!pip install --upgrade praw

Requirement already satisfied: praw in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (8.0.0)
Collecting praw
  Downloading praw-8.0.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: defusedxml==0.7.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (0.7.1)
Requirement already satisfied: prawcore<5,>=4 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (4.0.0)
Requirement already satisfied: update-checker<2.0,>=1.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (1.0.0)
Requirement already satisfied: websocket-client<2,>=0.54.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from praw) (1.8.0)
Requirement already satisfied: requests<3.0,>=2.34.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from prawcore<5,>=4->praw) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2025.1.31)
Downloading praw-8.0.1-py3-none-any.whl (199 kB)
Installing collected packages: praw
  Attempting uninstall: praw
    Found existing installation: praw 8.0.0
    Uninstalling praw-8.0.0:
      Successfully uninstalled praw-8.0.0
Successfully installed praw-8.0.1

In [48]:
reddit = praw.Reddit(
    client_id="6o5Pai7oa3CQhvbOO9z9SA",
    client_secret="_Eg7OvGzRvdTlqdZ4KFSjgjNkQT4BQ",
    user_agent="avis_app"
)

In [49]:
subreddit = reddit.subreddit("productreviews")

In [50]:
data = []

In [ ]:
for post in subreddit.hot(limit=1000):

_IncompleteInputError: incomplete input (394247696.py, line 1)

:

In [51]:
for post in subreddit.hot(limit=1000):
    print(post.title)
    print(post.selftext)
    print("-----")

Introducing a new rewards system for honest, in-depth product reviews
There are no incentives for consumers to write honest in-depth reviews on platforms like Amazon. Why would you produce content for a retailer for free? Many sellers started giving out free products in exchange for positive reviews, which was the start of the whole fake reviews crisis.

People now come to Reddit for reviews because Redditors and other forum members are interested in boosting their ego by showing their depth of knowledge on the topic (and correcting others on the topic).

We're now announcing a new rewards system for high-quality reviews on our subreddit! This system is designed to incentivize users to write detailed, well-written reviews that provide valuable information to other users.

Here's how it will work:

* Users who write reviews will earn points based on the quality of their reviews. The points will be determined by a combination of factors such as the length and detail of the review, the overall helpfulness of the review to other users, and the number of upvotes or positive feedback the review receives.
* Users then get a chance to win a gift cards or discount each month. It's entirely crowdfunded and we start with $100 for January.
* We have strong policies to ensure the authenticity and integrity of the reviews. More on that in another post.

We hope you'll join us in this effort to improve the quality of reviews on reddit, and we look forward to seeing all of the great reviews you'll be sharing with the community!
-----
The Best Genmaicha Tea Brands of the Year
Genmaicha is a traditional Japanese tea that blends green tea with roasted brown rice.
-----
First time drinking Rammstein Rum!
[https://youtu.be/Qx2c7V6gUNA](https://youtu.be/Qx2c7V6gUNA)
-----
IKEA Stenkol Battery Charger Review
I have been using my Duracell CEF14 battery charger to charge my Panasonic EVOLTA and IKEA Ladda batteries for a long time. For some reason, my CEF14 charger started not to charge my IKEA batteries fully and decided to buy IKEA STENKOL charger. I’m using it for about 6 months and this time is enough to make [IKEA Stenkol battery charger review](https://www.izreview.com/ikea-stenkol-battery-charger-review/).


-----
Café Bustelo Coffee Review

-----
Café Bustelo Coffee Review

-----
The Best Kenyan Coffee Bean Brands of the Year

-----
A List of Popular Peaberry Coffee Bean Brands

-----
The Best Osmanthus Tea Brands of 2024

-----
Verdant Tea Big Red Robe Wuyi Oolong Tea Review

-----
The Best Tulsi (Holy Basil) Tea Brands of 2023

-----
Best Apps to Watch Anime for Free - Top 15

-----
The best glass cleaner I have come across
This stuff is amazing. When you spray it on, it foams up a little bit. Give it a few seconds and then wipe the foam off with a cloth rag. It doesn’t damage the windows at all, and because it works so well, you really only have to use it once every few weeks or so.
-----
Laundry Sauce Pods: Honest reviews from actual customers???

-----
Frigidaire professional refrigerators are horrible and customer service is awful
A warning about buying ANY product from Frigidaire. On October 7, 2020 we remodeled our kitchen and purchased a new Frigidaire Professional model #PRMC2285AF.  In December 2022 the refrigerator failed and would not cool.

A service call to a provider from the Frigidaire web site resulted in a determination the failure was the compressor. At two years old the compressor of a $3500 refrigerator stops working?? The service repairman indicated the part was covered since it was a part of the “closed system.” A couple weeks later we get a call from that same company now explaining the part is not covered.

Ultimately, following numerous calls and emails we decided to give up and pay for the repairs.  On January 26 we paid over $1,000 for the refrigerator to be fixed. The repairs were directly with Electrolux Home Products, Inc., 10200 David Taylor Drive, Charlotte, NC.

On February 4, 2023 1:52 pm I sent an email seeking an update on when I could expect the repair to take place. No reply.  On February 7 at 9:14 pm I again sent an email seeking clarification on when the refrigerator would be repaired. Again, no response.

On March 2 at 11:33 am I called Electrolux 1 855 224-4987 to seek an update. I was told they had no timeframe as to when they would be able to fix the refrigerator.

I tried the chat option and communicated with “Mark” on March 2 between 12:16 pm and 12:34 pm. Ultimately “Mark” told me he had no information as to when I could expect the repair to take place.

I asked the following question:
“So you have no information? I am just supposed to wait for some unspecified time to “hope” you finally fix my refrigerator at some point?”

Mark’s two word reply was “Yes Kevin.”

Keep in mind this is their help line and that is their attitude towards people who purchased their products!!

I received a call from Frigidaire on March 20 at 1:15 pm and was informed that they “hoped to have the part by May 15.”

I followed up today March 28 and spoke eith Shea. I was told they were not sure when the refrigerator would be fixed but they hoped the part would be available in May.

The lack of customer service by Electrolux is as reprehensible as any company I’ve ever worked with. I will never, and I would caution others, to seek other appliance manufacturers who actually care about their customers. In addition, seek out alternatives to Electrolux as the failure of a critical and expensive part of the unit failing in only 2 years is not acceptable in my view.
-----
Skullshaver by Pitbull
Don’t fall for there ads. I bought a Skullshaver pitbull Gold about a year ago. In the first shave of my nearly bald head with the product the blades locked up and the shaver just stopped working.

I contacted there customer support and they had me ship the defective blade back to them and sent me a knew one fairly quick. The issue was this blade did the exact same.

I even Pre Shaved my longer hair with a regular shaver before using it scared the longer hair was the issue. You shouldn’t have to Pre Shave to use a shaver and it didn’t help half way through my shave the blades once again locked up and froze in place. At this point I was just fed up with it and put it to the side to busy to deal with it.

Then came the Unrelenting ads. Id get nothing but Pitbull shavers on my Facebook feed emails daily selling me more products. Id request to be removed and they would stop for a month before a new batch would flood in. I even spam blocked them and somehow they kept getting through.

Well im sick of it i wasted nearly 100$ on this product and Nobody seems to give them any bad reviews. I am. Don’t waste your money the shaver Dose Not Work…
-----
Washer/Dryer combo units. Problems, things to look out for? Are they quiet enough? I'm looking specifically at Samsung 8.5kg/6kg Washer Dryer Combo WD85T4046CE. Go for it or think twice?

-----
Thinking of getting one of these car HUD’s. Has anyone got one? Would be keen to see a review.

-----
Jabra Evolve 75 UC headset lasted 2 years before the microphone stopped working

-----
SOG Powertool - Free for life! Issued by the military, been around the world and replaced for free by SOG when it wore out without any quibbles!

-----
Had a pair of vintage Snap On pliers that weren't cutting it anymore - Snap On's lifetime guarantee sent me a new pair for free

-----
Glorious Model O- mouse still going strong after 2.5 years of use
**Condition:** Still In Use

**Years Owned:** 2.5 years

**Usage:** Daily

**Stress points:** Couple LEDS turned turquoise. Most of the time RGB was set to pinkish color. Even changed DPI led to the same color, no difference.

**Positive Remarks:** \-

* Side buttons are nice, good placement.
* Having option to save 3 DPI settings and choosing color for each one.
* On the pic it wasn't cleaned but for the past 2.5 years I did open the palm part couple of times and cleaned it.

**Price Paid:** $40   **Cost per Month:** $1.33

**Would you buy it again?** Yes

[View Post](https://www.looria.com/reviews/details/geforce-rtx-2080-super-8gb-rog-strix/63b92cb922bc1d000403bba9)

[Submit a longevity review](https://www.looria.com/reviews/submission)
-----
Asus GeForce RTX 2080 SUPER 8GB ROG STRIX review after 3 years of use
**Condition:** Still In Use

**Years Owned:** 3 years

**Usage:** Daily

**Stress points:** Fans rattles loudly at loads while gaming. (extremely prevalent on these strix coolers) Coilwhine

**Positive Remarks:** Temps are good

**Would you buy it again?** No

[View Post](https://www.looria.com/reviews/details/geforce-rtx-2080-super-8gb-rog-strix/63b92cb922bc1d000403bba9)

[Submit a review](https://www.looria.com/reviews/submission)
-----
What are some scathing reviews you’ve seen for objects you wouldn’t expect people to get so passionate about?

-----
Grip 6 Ninja Belt still going strong after 4 years of use - no moving parts that can break

-----
Felco 2 Pruning Shears still going strong after 3 years of use - great grip and very durable
**Condition:** Still In Use

**Years Owned:** 3 years

**Usage:** Weekly

**Positive Remarks:** Great grip and very durable. Precision made, and you can get every replacement part from Felco.

**Negative Remarks:** None so far

**Price Paid:** $60   **Cost per Month:** $1.67

**Would you buy it again?** Yes

https://preview.redd.it/2fvvt1892v6a1.png?width=1000&format=png&auto=webp&s=60f2ae340e3d05810f251039e321a2fd12727e89

[View Post](https://www.exitreviews.com/details/2-pruning-shear/639dc657f4dd9500042ebe83)

[Submit a longevity review](https://www.looria.com/reviews/submission)

What's your experience with Felco products or alternatives?
-----
How is r/ProductReviews different from r/BuyItForLife?
Since people pointed out that this sub is similar to r/BuyItForLife, I want to explain how and why we're different:

**The main frustrations with** r/BuyItForLife

1. Products that aren’t available for purchase anymore
2. Mostly USA related
3. Finding specific products/ Database system/ Bad search
4. Repetitive posts/requests
5. Old products that are unused/not frequently used
6. Hard to track changing opinions on brands over the years
7. It's centered around certain categories
8. Finding affordable options

As some user put it:

* "Of course your fucking hammer works 20 years later shieeet"
* "It's mostly people bragging about old staplers"
* "Endless pictures of peoples' old belts and coffee grinders."
* "People posting their great-grandparents' Black & Decker boasting how "it's still chugging along and they don't make them like this anymore"
* "Mostly products from 60s, or complaints about change"
* "do the people with 30 year old microwave ovens know that it doesn't take 25 minutes for a frozen lasagna to cook?"

**We want to address these points.**

* We're focused on structured longevity reviews that allow us to calculate metrics like the cost of ownership per month, what % would buy it again, etc.
* Our Reddit bot will send you a reminder to update the status of your product reviews regularly (customizable interval)
* We have a crowdsourced database with all the reviews, which makes finding and researching products and brands very easy. Even if a product is not available anymore, the data is still useful on an aggregated brand level.
* We try to avoid posts of very ancient products that are barely used.
-----
Moer Sky Dog Training Collar, Upgraded 100% Waterproof Rechargeable

-----
Have Conformed Nicely to My Feet

-----
My 10 year old sons unboxing and attempted review of Blue snowball ice mic and Elgato game capture
https://youtu.be/LSK62ZcHiYA
-----
Not the Best Grinder, But a Terrific Collectable & Conversation Starter

-----
Plush, Sturdy Door Mat - Not a Thin, Easy-to-Wear-Through Mat

-----
Individual Motion Detector Ideal For Little Used Door Or Exterior Building

-----
My Dogs Do NOT Respond to Shock, But the Tone Makes Them Pay Attention

-----
I’ve Mentioned My Knee Other Times, This is One More Trial at Finding the Best Knee Sleeve

-----
Been Wanting Something Like this Awhile, Finally Found the Right One

-----
What a Great Toy for Many Ages

-----
Mynt Shiatsu Massage Pillow

-----
Black Box Unboxing | Black Box 2017 | #BlackBox #BlackBoxAU

-----
2nd Charcoal Mask I’ve Tried

-----
Awesome Hunting Gear Review.

-----
Funny Pool Poop emoji review!

-----
AWESOME INEXPENSIVE COMPRESSOR REVIEW

-----
GOOD Water Shoes, NOT Cheapo Crap

-----
Baby Jogger 2016 City Mini Double Stroller Review

-----
Seriously Well Made Clipper Set Can Save HUNDREDS of Dollars in Pet Grooming

-----
Iphone Case made from body armor material.

-----
You a 90s kid?
What memory you have of the 90's? I almost went rolling on the floor asking my nephew if he knows (me SHOWING HIM A CASSETTE RECORDER) how to record on a cassette tape.
-----
BEEN Wanting Something Like this but No Auxiliary Port

-----
Nice Addition To Kitchen Knife Collection

-----
Really Neat Device

-----
Here I give a review on the all too famous "Inflatable Lounger" We all have our opinions, here's mine...with a twist!

-----
I Got Mom One for Her Health

-----
Best DustBuster For Hardwood Floors Reviews 2017

-----
Innovative Air Freshener - Not Ordinary Convenient Store Air Freshener

-----
I Don’t Even Want to Get This Dirty

-----
My Nephew (and My Brother) LOVES These Things!!

-----
Wish ALL My Tarps Were This Thick and Durable

-----
Budget microphone for new film makers!

-----
Thought I Had Found the BEST Before, THIS Is The Better of the Two!

-----
Got This For Mom and She is in LOVE!

-----
Tried Several - These are Terrific!

-----
One Outlet At A Time - Got The Single To Start

-----
Terrific Stuff - According to Mom & What I See it Has Done

-----
iPhone Lens 7 Plus Kit Puts all Your Camera Needs Into One Device

-----
Healthy, Beautiful AFFORDABLE Himalayan Salt Lamp

-----
wtf?? charcoal for teeth whitening?

-----
Got for Mom and She LOVES It

-----
Type-C Adapter has Many Uses

-----
Heard Lots, Just HAD to Try

-----
Hoping My Cats Are Enjoying

-----
Super Comfortable, I Sleep Like Baby

-----
Best Wired Phone Headset Reviews and Comparison 2017

-----
Essential Oils are Just That - Essential

-----
Testing Various Meat Thermometers - This One has Great Features
I have been testing various meat thermometers as I learn the art of smoking various meats and this one has come very unique features. When the prong is extended, the thermometer automatically turns on. This is the fastest of all the thermometers I have tested reading in as few as 4 seconds so no waiting. It reads the temperature aloud to you so you needn’t stick your head in the hot oven or over the coals although it has a bright LCD screen with a digital readout. The retractable probe makes storage a synch and once closed,  turns off automatically. This comes in a nice box along with a temperature chart, manual, Velcro circles for hanging in an out-of-the-way place. A lifetime warranty makes this a very good deal as well as a very good cooking thermometer.

#McNeilGraphix #PurchasesMadeSimple #Amazon #AmazonPrime #Kizen #KizenDigitalMeat&CookingThermometer

-----
Low Standing Won’t Break at the Base Like the Last One - Great!

-----
Got for Mom and She LOVES It
I simply LOVE tops like this! I do not want clingy so this long, tunic-ike top drapes perfectly on me, is super stretchy, and no risk of shrinkage. I cannot wait for the Fall weather to begin wearing this over leggings. THESE are the type clothes I like - loose fitting, not clingy, not accentuating anything but hanging loosely over my behind and perfect for leggings! Colors are a warm  I am a cool but this doesn’t look bad on me, no one thinks, as the peach is not orange and black and white work for anyone. Black leggings & boots or flats - make for a really cute look.

#McNeilGraphix #PurchasesMadeSimple #Amazon #AmazonPrime #ENJOYNIGHT #ENJOYNIGHTWomensCasual
-----
Glacial mud Mask Trial - NuSkin
I was hesitant to use anything on my face as i'd suffer with zits or allergies if the product is harsh or "incompatible" with my skin. So I asked if a trial pack is available and they do have and skin patch test it first, no reaction. Product label says its all natural. So after finally putting it on my face, I felt a bit of sting and tightening I kinda panicked and wanted to take it off immediately but I have read that it is part of the cleansing, so I went on drying it up on my face and then rinsed it after the required time to leave it on my skin. I didn't find the experience enjoyable like the other masks I would get over the counter, because of the sting, maybe. But I would like to try it again, this maybe a product that needs frequent using before you find any changes or satisfactory result.
-----
What are some really cool food products/kitchen gadgets that are out there?
Looking to try out some new products in the kitchen and was wondering if anyone has stumbled across anything new or interesting recently.
-----
Ever Been Swimming and Wound Up with Very Dry Skin?

-----
Tactical CREE LED Flashlight Review - LUMIZOOM LZ250g

-----
They Said it Can't Be Ripped...

-----

In [52]:
for post in subreddit.hot(limit=10000):
    data.append({
        "title": post.title,
        "text": post.selftext,
        "score": post.score
    })

In [53]:
print(len(data))

82

In [2]:
from pymongo import MongoClient

In [3]:
clean_data = []

for post in data:
    if post["title"] and post["text"] is not None:
        clean_data.append(post)

NameError: name 'data' is not defined

In [4]:
client = MongoClient("mongodb://localhost:27017/")
db = client["reddit_db"]
collection = db["reviews"]

In [5]:
result = collection.insert_many(clean_data)

print(len(result.inserted_ids))

TypeError: documents must be a non-empty list

In [58]:
for doc in collection.find():
    print(doc)

{'_id': ObjectId('6a31aeb5f18335f172f76285'), 'title': 'Introducing a new rewards system for honest, in-depth product reviews', 'text': "There are no incentives for consumers to write honest in-depth reviews on platforms like Amazon. Why would you produce content for a retailer for free? Many sellers started giving out free products in exchange for positive reviews, which was the start of the whole fake reviews crisis.\n\nPeople now come to Reddit for reviews because Redditors and other forum members are interested in boosting their ego by showing their depth of knowledge on the topic (and correcting others on the topic).\n\nWe're now announcing a new rewards system for high-quality reviews on our subreddit! This system is designed to incentivize users to write detailed, well-written reviews that provide valuable information to other users.\n\nHere's how it will work:\n\n* Users who write reviews will earn points based on the quality of their reviews. The points will be determined by a combination of factors such as the length and detail of the review, the overall helpfulness of the review to other users, and the number of upvotes or positive feedback the review receives.\n* Users then get a chance to win a gift cards or discount each month. It's entirely crowdfunded and we start with $100 for January.\n* We have strong policies to ensure the authenticity and integrity of the reviews. More on that in another post.\n\nWe hope you'll join us in this effort to improve the quality of reviews on reddit, and we look forward to seeing all of the great reviews you'll be sharing with the community!", 'score': 14}
{'_id': ObjectId('6a31aeb5f18335f172f76286'), 'title': 'The Best Genmaicha Tea Brands of the Year', 'text': 'Genmaicha is a traditional Japanese tea that blends green tea with roasted brown rice.', 'score': 3}
{'_id': ObjectId('6a31aeb5f18335f172f76287'), 'title': 'First time drinking Rammstein Rum!', 'text': '[https://youtu.be/Qx2c7V6gUNA](https://youtu.be/Qx2c7V6gUNA)', 'score': 3}
{'_id': ObjectId('6a31aeb5f18335f172f76288'), 'title': 'IKEA Stenkol Battery Charger Review', 'text': 'I have been using my Duracell CEF14 battery charger to charge my Panasonic EVOLTA and\xa0IKEA Ladda batteries\xa0for a long time. For some reason, my CEF14 charger started not to charge my IKEA batteries fully and decided to buy IKEA STENKOL charger. I’m using it for about 6 months and this time is enough to make [IKEA Stenkol battery charger review](https://www.izreview.com/ikea-stenkol-battery-charger-review/).\n\n', 'score': 3}
{'_id': ObjectId('6a31aeb5f18335f172f76289'), 'title': 'Café Bustelo Coffee Review', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f7628a'), 'title': 'Café Bustelo Coffee Review', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f7628b'), 'title': 'The Best Kenyan Coffee Bean Brands of the Year', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f7628c'), 'title': 'A List of Popular Peaberry Coffee Bean Brands', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f7628d'), 'title': 'The Best Osmanthus Tea Brands of 2024', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f7628e'), 'title': 'Verdant Tea Big Red Robe Wuyi Oolong Tea Review', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f7628f'), 'title': 'The Best Tulsi (Holy Basil) Tea Brands of 2023', 'text': '', 'score': 4}
{'_id': ObjectId('6a31aeb5f18335f172f76290'), 'title': 'Best Apps to Watch Anime for Free - Top 15', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f76291'), 'title': 'The best glass cleaner I have come across', 'text': 'This stuff is amazing. When you spray it on, it foams up a little bit. Give it a few seconds and then wipe the foam off with a cloth rag. It doesn’t damage the windows at all, and because it works so well, you really only have to use it once every few weeks or so.', 'score': 23}
{'_id': ObjectId('6a31aeb5f18335f172f76292'), 'title': 'Laundry Sauce Pods: Honest reviews from actual customers???', 'text': '', 'score': 31}
{'_id': ObjectId('6a31aeb5f18335f172f76293'), 'title': 'Frigidaire professional refrigerators are horrible and customer service is awful', 'text': 'A warning about buying ANY product from Frigidaire. On October 7, 2020 we remodeled our kitchen and purchased a new Frigidaire Professional model #PRMC2285AF.  In December 2022 the refrigerator failed and would not cool. \n\nA service call to a provider from the Frigidaire web site resulted in a determination the failure was the compressor. At two years old the compressor of a $3500 refrigerator stops working?? The service repairman indicated the part was covered since it was a part of the “closed system.” A couple weeks later we get a call from that same company now explaining the part is not covered.\n\nUltimately, following numerous calls and emails we decided to give up and pay for the repairs.  On January 26 we paid over $1,000 for the refrigerator to be fixed. The repairs were directly with Electrolux Home Products, Inc., 10200 David Taylor Drive, Charlotte, NC.\n\nOn February 4, 2023 1:52 pm I sent an email seeking an update on when I could expect the repair to take place. No reply.  On February 7 at 9:14 pm I again sent an email seeking clarification on when the refrigerator would be repaired. Again, no response.\n\nOn March 2 at 11:33 am I called Electrolux 1 855 224-4987 to seek an update. I was told they had no timeframe as to when they would be able to fix the refrigerator.\n\nI tried the chat option and communicated with “Mark” on March 2 between 12:16 pm and 12:34 pm. Ultimately “Mark” told me he had no information as to when I could expect the repair to take place.\n\nI asked the following question:\n“So you have no information? I am just supposed to wait for some unspecified time to “hope” you finally fix my refrigerator at some point?”\n\nMark’s two word reply was “Yes Kevin.”\n\nKeep in mind this is their help line and that is their attitude towards people who purchased their products!! \n\nI received a call from Frigidaire on March 20 at 1:15 pm and was informed that they “hoped to have the part by May 15.”\n\nI followed up today March 28 and spoke eith Shea. I was told they were not sure when the refrigerator would be fixed but they hoped the part would be available in May.\n\nThe lack of customer service by Electrolux is as reprehensible as any company I’ve ever worked with. I will never, and I would caution others, to seek other appliance manufacturers who actually care about their customers. In addition, seek out alternatives to Electrolux as the failure of a critical and expensive part of the unit failing in only 2 years is not acceptable in my view.', 'score': 16}
{'_id': ObjectId('6a31aeb5f18335f172f76294'), 'title': 'Skullshaver by Pitbull', 'text': 'Don’t fall for there ads. I bought a Skullshaver pitbull Gold about a year ago. In the first shave of my nearly bald head with the product the blades locked up and the shaver just stopped working. \n\nI contacted there customer support and they had me ship the defective blade back to them and sent me a knew one fairly quick. The issue was this blade did the exact same. \n\nI even Pre Shaved my longer hair with a regular shaver before using it scared the longer hair was the issue. You shouldn’t have to Pre Shave to use a shaver and it didn’t help half way through my shave the blades once again locked up and froze in place. At this point I was just fed up with it and put it to the side to busy to deal with it.\n\nThen came the Unrelenting ads. Id get nothing but Pitbull shavers on my Facebook feed emails daily selling me more products. Id request to be removed and they would stop for a month before a new batch would flood in. I even spam blocked them and somehow they kept getting through.\n\nWell im sick of it i wasted nearly 100$ on this product and Nobody seems to give them any bad reviews. I am. Don’t waste your money the shaver Dose Not Work…', 'score': 9}
{'_id': ObjectId('6a31aeb5f18335f172f76295'), 'title': "Washer/Dryer combo units. Problems, things to look out for? Are they quiet enough? I'm looking specifically at Samsung 8.5kg/6kg Washer Dryer Combo WD85T4046CE. Go for it or think twice?", 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f76296'), 'title': 'Thinking of getting one of these car HUD’s. Has anyone got one? Would be keen to see a review.', 'text': '', 'score': 9}
{'_id': ObjectId('6a31aeb5f18335f172f76297'), 'title': 'Jabra Evolve 75 UC headset lasted 2 years before the microphone stopped working', 'text': '', 'score': 6}
{'_id': ObjectId('6a31aeb5f18335f172f76298'), 'title': 'SOG Powertool - Free for life! Issued by the military, been around the world and replaced for free by SOG when it wore out without any quibbles!', 'text': '', 'score': 4}
{'_id': ObjectId('6a31aeb5f18335f172f76299'), 'title': "Had a pair of vintage Snap On pliers that weren't cutting it anymore - Snap On's lifetime guarantee sent me a new pair for free", 'text': '', 'score': 6}
{'_id': ObjectId('6a31aeb5f18335f172f7629a'), 'title': 'Glorious Model O- mouse still going strong after 2.5 years of use', 'text': "**Condition:** Still In Use\n\n**Years Owned:** 2.5 years\n\n**Usage:** Daily\n\n**Stress points:** Couple LEDS turned turquoise. Most of the time RGB was set to pinkish color. Even changed DPI led to the same color, no difference.\n\n**Positive Remarks:** \\- \n\n* Side buttons are nice, good placement.\n* Having option to save 3 DPI settings and choosing color for each one.\n* On the pic it wasn't cleaned but for the past 2.5 years I did open the palm part couple of times and cleaned it.\n\n**Price Paid:** $40   **Cost per Month:** $1.33\n\n**Would you buy it again?** Yes\n\n[View Post](https://www.looria.com/reviews/details/geforce-rtx-2080-super-8gb-rog-strix/63b92cb922bc1d000403bba9)\n\n[Submit a longevity review](https://www.looria.com/reviews/submission)", 'score': 3}
{'_id': ObjectId('6a31aeb5f18335f172f7629b'), 'title': 'Asus GeForce RTX 2080 SUPER 8GB ROG STRIX review after 3 years of use', 'text': '**Condition:** Still In Use\n\n**Years Owned:** 3 years\n\n**Usage:** Daily\n\n**Stress points:** Fans rattles loudly at loads while gaming. (extremely prevalent on these strix coolers) Coilwhine\n\n**Positive Remarks:** Temps are good\n\n**Would you buy it again?** No\n\n[View Post](https://www.looria.com/reviews/details/geforce-rtx-2080-super-8gb-rog-strix/63b92cb922bc1d000403bba9)\n\n[Submit a review](https://www.looria.com/reviews/submission)', 'score': 6}
{'_id': ObjectId('6a31aeb5f18335f172f7629c'), 'title': 'What are some scathing reviews you’ve seen for objects you wouldn’t expect people to get so passionate about?', 'text': '', 'score': 7}
{'_id': ObjectId('6a31aeb5f18335f172f7629d'), 'title': 'Grip 6 Ninja Belt still going strong after 4 years of use - no moving parts that can break', 'text': '', 'score': 10}
{'_id': ObjectId('6a31aeb5f18335f172f7629e'), 'title': 'Felco 2 Pruning Shears still going strong after 3 years of use - great grip and very durable', 'text': "**Condition:** Still In Use\n\n**Years Owned:** 3 years\n\n**Usage:** Weekly\n\n**Positive Remarks:** Great grip and very durable. Precision made, and you can get every replacement part from Felco.\n\n**Negative Remarks:** None so far\n\n**Price Paid:** $60   **Cost per Month:** $1.67\n\n**Would you buy it again?** Yes\n\nhttps://preview.redd.it/2fvvt1892v6a1.png?width=1000&format=png&auto=webp&s=60f2ae340e3d05810f251039e321a2fd12727e89\n\n[View Post](https://www.exitreviews.com/details/2-pruning-shear/639dc657f4dd9500042ebe83)\n\n[Submit a longevity review](https://www.looria.com/reviews/submission)\n\nWhat's your experience with Felco products or alternatives?", 'score': 12}
{'_id': ObjectId('6a31aeb5f18335f172f7629f'), 'title': 'How is r/ProductReviews different from r/BuyItForLife?', 'text': 'Since people pointed out that this sub is similar to r/BuyItForLife, I want to explain how and why we\'re different:\n\n**The main frustrations with** r/BuyItForLife\n\n1. Products that aren’t available for purchase anymore\n2. Mostly USA related\n3. Finding specific products/ Database system/ Bad search\n4. Repetitive posts/requests\n5. Old products that are unused/not frequently used\n6. Hard to track changing opinions on brands over the years\n7. It\'s centered around certain categories\n8. Finding affordable options\n\nAs some user put it:\n\n* "Of course your fucking hammer works 20 years later shieeet"\n* "It\'s mostly people bragging about old staplers"\n* "Endless pictures of peoples\' old belts and coffee grinders."\n* "People posting their great-grandparents\' Black & Decker boasting how "it\'s still chugging along and they don\'t make them like this anymore"\n* "Mostly products from 60s, or complaints about change"\n* "do the people with 30 year old microwave ovens know that it doesn\'t take 25 minutes for a frozen lasagna to cook?"\n\n**We want to address these points.**\n\n* We\'re focused on structured longevity reviews that allow us to calculate metrics like the cost of ownership per month, what % would buy it again, etc.\n* Our Reddit bot will send you a reminder to update the status of your product reviews regularly (customizable interval)\n* We have a crowdsourced database with all the reviews, which makes finding and researching products and brands very easy. Even if a product is not available anymore, the data is still useful on an aggregated brand level.\n* We try to avoid posts of very ancient products that are barely used.', 'score': 17}
{'_id': ObjectId('6a31aeb5f18335f172f762a0'), 'title': 'Moer Sky Dog Training Collar, Upgraded 100% Waterproof Rechargeable', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a1'), 'title': 'Have Conformed Nicely to My Feet', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a2'), 'title': 'My 10 year old sons unboxing and attempted review of Blue snowball ice mic and Elgato game capture', 'text': 'https://youtu.be/LSK62ZcHiYA', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a3'), 'title': 'Not the Best Grinder, But a Terrific Collectable & Conversation Starter', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762a4'), 'title': 'Plush, Sturdy Door Mat - Not a Thin, Easy-to-Wear-Through Mat', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762a5'), 'title': 'Individual Motion Detector Ideal For Little Used Door Or Exterior Building', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a6'), 'title': 'My Dogs Do NOT Respond to Shock, But the Tone Makes Them Pay Attention', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762a7'), 'title': 'I’ve Mentioned My Knee Other Times, This is One More Trial at Finding the Best Knee Sleeve', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a8'), 'title': 'Been Wanting Something Like this Awhile, Finally Found the Right One', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762a9'), 'title': 'What a Great Toy for Many Ages', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762aa'), 'title': 'Mynt Shiatsu Massage Pillow', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762ab'), 'title': 'Black Box Unboxing | Black Box 2017 | #BlackBox #BlackBoxAU', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762ac'), 'title': '2nd Charcoal Mask I’ve Tried', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762ad'), 'title': 'Awesome Hunting Gear Review.', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762ae'), 'title': 'Funny Pool Poop emoji review!', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762af'), 'title': 'AWESOME INEXPENSIVE COMPRESSOR REVIEW', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b0'), 'title': 'GOOD Water Shoes, NOT Cheapo Crap', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762b1'), 'title': 'Baby Jogger 2016 City Mini Double Stroller Review', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b2'), 'title': 'Seriously Well Made Clipper Set Can Save HUNDREDS of Dollars in Pet Grooming', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b3'), 'title': 'Iphone Case made from body armor material.', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b4'), 'title': 'You a 90s kid?', 'text': "What memory you have of the 90's? I almost went rolling on the floor asking my nephew if he knows (me SHOWING HIM A CASSETTE RECORDER) how to record on a cassette tape.", 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b5'), 'title': 'BEEN Wanting Something Like this but No Auxiliary Port', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b6'), 'title': 'Nice Addition To Kitchen Knife Collection', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b7'), 'title': 'Really Neat Device', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b8'), 'title': 'Here I give a review on the all too famous "Inflatable Lounger" We all have our opinions, here\'s mine...with a twist!', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762b9'), 'title': 'I Got Mom One for Her Health', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762ba'), 'title': 'Best DustBuster For Hardwood Floors Reviews 2017', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762bb'), 'title': 'Innovative Air Freshener - Not Ordinary Convenient Store Air Freshener', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762bc'), 'title': 'I Don’t Even Want to Get This Dirty', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762bd'), 'title': 'My Nephew (and My Brother) LOVES These Things!!', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762be'), 'title': 'Wish ALL My Tarps Were This Thick and Durable', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762bf'), 'title': 'Budget microphone for new film makers!', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762c0'), 'title': 'Thought I Had Found the BEST Before, THIS Is The Better of the Two!', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762c1'), 'title': 'Got This For Mom and She is in LOVE!', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762c2'), 'title': 'Tried Several - These are Terrific!', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762c3'), 'title': 'One Outlet At A Time - Got The Single To Start', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762c4'), 'title': 'Terrific Stuff - According to Mom & What I See it Has Done', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762c5'), 'title': 'iPhone Lens 7 Plus Kit Puts all Your Camera Needs Into One Device', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762c6'), 'title': 'Healthy, Beautiful AFFORDABLE Himalayan Salt Lamp', 'text': '', 'score': 2}
{'_id': ObjectId('6a31aeb5f18335f172f762c7'), 'title': 'wtf?? charcoal for teeth whitening?', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762c8'), 'title': 'Got for Mom and She LOVES It', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762c9'), 'title': 'Type-C Adapter has Many Uses', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762ca'), 'title': 'Heard Lots, Just HAD to Try', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762cb'), 'title': 'Hoping My Cats Are Enjoying', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762cc'), 'title': 'Super Comfortable, I Sleep Like Baby', 'text': '', 'score': 0}
{'_id': ObjectId('6a31aeb5f18335f172f762cd'), 'title': 'Best Wired Phone Headset Reviews and Comparison 2017', 'text': '', 'score': 1}
{'_id': ObjectId('6a31aeb5f18335f172f762ce'), 'title': 'Essential Oils are Just That - Essential', 'text': '', 'score': 1}

In [6]:
collection.count_documents({})

82

In [9]:
import pandas as pd

data = list(collection.find())

df = pd.DataFrame(data)

df.head()

,_id,title,text,score
0,6a31aeb5f18335f172f76285,"Introducing a new rewards system for honest, i...",There are no incentives for consumers to write...,14
1,6a31aeb5f18335f172f76286,The Best Genmaicha Tea Brands of the Year,Genmaicha is a traditional Japanese tea that b...,3
2,6a31aeb5f18335f172f76287,First time drinking Rammstein Rum!,[https://youtu.be/Qx2c7V6gUNA](https://youtu.b...,3
3,6a31aeb5f18335f172f76288,IKEA Stenkol Battery Charger Review,I have been using my Duracell CEF14 battery ch...,3
4,6a31aeb5f18335f172f76289,Café Bustelo Coffee Review,,2

In [10]:
print(df.columns)

Index(['_id', 'title', 'text', 'score'], dtype='str')

In [11]:
df = df.drop(columns=["_id"])

In [12]:
df.head()

,title,text,score
0,"Introducing a new rewards system for honest, i...",There are no incentives for consumers to write...,14
1,The Best Genmaicha Tea Brands of the Year,Genmaicha is a traditional Japanese tea that b...,3
2,First time drinking Rammstein Rum!,[https://youtu.be/Qx2c7V6gUNA](https://youtu.b...,3
3,IKEA Stenkol Battery Charger Review,I have been using my Duracell CEF14 battery ch...,3
4,Café Bustelo Coffee Review,,2

In [13]:
print(df.isnull().sum())

title    0
text     0
score    0
dtype: int64

In [14]:
df["review"] = df["title"] + " " + df["text"]

In [15]:
print(df[["review"]].head())

                                              review
0  Introducing a new rewards system for honest, i...
1  The Best Genmaicha Tea Brands of the Year Genm...
2  First time drinking Rammstein Rum! [https://yo...
3  IKEA Stenkol Battery Charger Review I have bee...
4                        Café Bustelo Coffee Review

In [16]:
df["sentiment"] = df["score"].apply(
    lambda x: 1 if x > 0 else 0
)

In [17]:
print(df["sentiment"].value_counts())

sentiment
1    73
0     9
Name: count, dtype: int64

In [18]:
df.to_csv("reddit_clean.csv", index=False)

In [23]:
import sqlite3

conn = sqlite3.connect("reddit_warehouse.db")

ERROR! Session/line number was not unique in database. History logging moved to new session 1171

In [24]:
df.to_sql(
    "reviews",
    conn,
    if_exists="replace",
    index=False
)

82

In [25]:
query = "SELECT * FROM reviews LIMIT 5"

test = pd.read_sql(query, conn)

print(test)

                                               title  \
0  Introducing a new rewards system for honest, i...
1          The Best Genmaicha Tea Brands of the Year
2                 First time drinking Rammstein Rum!
3                IKEA Stenkol Battery Charger Review
4                         Café Bustelo Coffee Review

                                                text  score  \
0  There are no incentives for consumers to write...     14
1  Genmaicha is a traditional Japanese tea that b...      3
2  [https://youtu.be/Qx2c7V6gUNA](https://youtu.b...      3
3  I have been using my Duracell CEF14 battery ch...      3
4                                                         2

                                              review  sentiment
0  Introducing a new rewards system for honest, i...          1
1  The Best Genmaicha Tea Brands of the Year Genm...          1
2  First time drinking Rammstein Rum! [https://yo...          1
3  IKEA Stenkol Battery Charger Review I have bee...          1
4                        Café Bustelo Coffee Review           1

In [22]:
!pip install google-cloud-bigquery
!pip install pandas-gbq
!pip install pyarrow

Collecting google-cloud-bigquery
  Downloading google_cloud_bigquery-3.42.0-py3-none-any.whl.metadata (8.0 kB)
Collecting google-api-core<3.0.0,>=2.11.1 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading google_api_core-2.31.0-py3-none-any.whl.metadata (3.2 kB)
Collecting google-auth<3.0.0,>=2.14.1 (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading google_auth-2.55.0-py3-none-any.whl.metadata (5.1 kB)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery)
  Downloading google_cloud_core-2.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery)
  Downloading google_resumable_media-2.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: packaging>=24.2.0 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (25.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-cloud-bigquery) (2.34.2)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting protobuf<8.0.0,>=5.29.6 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting proto-plus<2.0.0,>=1.24.0 (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)
Collecting grpcio<2.0.0,>=1.41.0 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio-1.81.1-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting grpcio-status<2.0.0,>=1.41.0 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio_status-1.81.1-py3-none-any.whl.metadata (1.2 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading cryptography-49.0.0-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting pyopenssl>=20.0.0 (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading pyopenssl-26.3.0-py3-none-any.whl.metadata (22 kB)
Collecting google-crc32c<2.0.0,>=1.0.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery)
  Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.1.31)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from grpcio<2.0.0,>=1.41.0->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.12.2)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: pycparser in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.21)
Downloading google_cloud_bigquery-3.42.0-py3-none-any.whl (263 kB)
Downloading google_api_core-2.31.0-py3-none-any.whl (173 kB)
Downloading google_auth-2.55.0-py3-none-any.whl (252 kB)
Downloading google_cloud_core-2.6.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.10.0-py3-none-any.whl (81 kB)
Downloading cryptography-49.0.0-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.8 MB 723.9 kB/s eta 0:00:05
   -------- ------------------------------- 0.8/3.8 MB 749.3 kB/s eta 0:00:05
   -------- ------------------------------- 0.8/3.8 MB 749.3 kB/s eta 0:00:05
   ----------- ---------------------------- 1.0/3.8 MB 749.7 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/3.8 MB 765.1 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/3.8 MB 765.1 kB/s eta 0:00:04
   ---------------- ----------------------- 1.6/3.8 MB 767.1 kB/s eta 0:00:03
   ---------------- ----------------------- 1.6/3.8 MB 767.1 kB/s eta 0:00:03
   ------------------- -------------------- 1.8/3.8 MB 756.4 kB/s eta 0:00:03
   ---------------------- ----------------- 2.1/3.8 MB 745.1 kB/s eta 0:00:03
   ---------------------- ----------------- 2.1/3.8 MB 745.1 kB/s eta 0:00:03
   ------------------------ --------------- 2.4/3.8 MB 742.4 kB/s eta 0:00:02
   ------------------------ --------------- 2.4/3.8 MB 742.4 kB/s eta 0:00:02
   --------------------------- ------------ 2.6/3.8 MB 727.4 kB/s eta 0:00:02
   --------------------------- ------------ 2.6/3.8 MB 727.4 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 714.6 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 714.6 kB/s eta 0:00:02
   --------------------------------- ------ 3.1/3.8 MB 707.8 kB/s eta 0:00:01
   --------------------------------- ------ 3.1/3.8 MB 707.8 kB/s eta 0:00:01
   --------------------------------- ------ 3.1/3.8 MB 707.8 kB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 654.2 kB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 654.2 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 652.0 kB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 648.0 kB/s eta 0:00:00
Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl (34 kB)
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
Downloading grpcio-1.81.1-cp313-cp313-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.9 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.9 MB ? eta -:--:--
   ---- ----------------------------------- 0.5/4.9 MB 636.6 kB/s eta 0:00:07
   ---- ----------------------------------- 0.5/4.9 MB 636.6 kB/s eta 0:00:07
   ------ --------------------------------- 0.8/4.9 MB 666.5 kB/s eta 0:00:07
   ------ --------------------------------- 0.8/4.9 MB 666.5 kB/s eta 0:00:07
   -------- ------------------------------- 1.0/4.9 MB 683.5 kB/s eta 0:00:06
   ---------- ----------------------------- 1.3/4.9 MB 675.8 kB/s eta 0:00:06
   ---------- ----------------------------- 1.3/4.9 MB 675.8 kB/s eta 0:00:06
   ------------ --------------------------- 1.6/4.9 MB 675.5 kB/s eta 0:00:05
   ------------ --------------------------- 1.6/4.9 MB 675.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   -------------- ------------------------- 1.8/4.9 MB 673.5 kB/s eta 0:00:05
   ----------------- ---------------------- 2.1/4.9 MB 495.4 kB/s eta 0:00:06
   ----------------- ---------------------- 2.1/4.9 MB 495.4 kB/s eta 0:00:06
   ------------------- -------------------- 2.4/4.9 MB 521.8 kB/s eta 0:00:05
   ------------------- -------------------- 2.4/4.9 MB 521.8 kB/s eta 0:00:05
   --------------------- ------------------ 2.6/4.9 MB 536.3 kB/s eta 0:00:05
   ----------------------- ---------------- 2.9/4.9 MB 555.6 kB/s eta 0:00:04
   ----------------------- ---------------- 2.9/4.9 MB 555.6 kB/s eta 0:00:04
   ------------------------- -------------- 3.1/4.9 MB 569.8 kB/s eta 0:00:04
   --------------------------- ------------ 3.4/4.9 MB 583.1 kB/s eta 0:00:03
   --------------------------- ------------ 3.4/4.9 MB 583.1 kB/s eta 0:00:03
   ----------------------------- ---------- 3.7/4.9 MB 592.3 kB/s eta 0:00:03
   ------------------------------- -------- 3.9/4.9 MB 599.1 kB/s eta 0:00:02
   ------------------------------- -------- 3.9/4.9 MB 599.1 kB/s eta 0:00:02
   ---------------------------------- ----- 4.2/4.9 MB 605.6 kB/s eta 0:00:02
   ---------------------------------- ----- 4.2/4.9 MB 605.6 kB/s eta 0:00:02
   ------------------------------------ --- 4.5/4.9 MB 614.1 kB/s eta 0:00:01
   -------------------------------------- - 4.7/4.9 MB 622.3 kB/s eta 0:00:01
   -------------------------------------- - 4.7/4.9 MB 622.3 kB/s eta 0:00:01
   ---------------------------------------- 4.9/4.9 MB 622.7 kB/s eta 0:00:00
Downloading grpcio_status-1.81.1-py3-none-any.whl (14 kB)
Downloading proto_plus-1.28.0-py3-none-any.whl (50 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyopenssl-26.3.0-py3-none-any.whl (56 kB)
Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl (183 kB)
Downloading pyasn1-0.6.3-py3-none-any.whl (83 kB)
Installing collected packages: pyasn1, protobuf, grpcio, google-crc32c, cffi, pyasn1-modules, proto-plus, googleapis-common-protos, google-resumable-media, cryptography, pyopenssl, grpcio-status, google-auth, google-api-core, google-cloud-core, google-cloud-bigquery
  Attempting uninstall: cffi
    Found existing installation: cffi 1.17.1
    Uninstalling cffi-1.17.1:
      Successfully uninstalled cffi-1.17.1
Successfully installed cffi-2.0.0 cryptography-49.0.0 google-api-core-2.31.0 google-auth-2.55.0 google-cloud-bigquery-3.42.0 google-cloud-core-2.6.0 google-crc32c-1.8.0 google-resumable-media-2.10.0 googleapis-common-protos-1.75.0 grpcio-1.81.1 grpcio-status-1.81.1 proto-plus-1.28.0 protobuf-7.35.1 pyasn1-0.6.3 pyasn1-modules-0.4.2 pyopenssl-26.3.0
Collecting pandas-gbq
  Downloading pandas_gbq-0.35.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: setuptools in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (75.8.0)
Collecting db-dtypes<2.0.0,>=1.1.1 (from pandas-gbq)
  Downloading db_dtypes-1.7.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy>=1.26.4 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (2.4.6)
Requirement already satisfied: pandas>=1.5.3 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (3.0.3)
Collecting pyarrow>=12.0.0 (from pandas-gbq)
  Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Collecting pydata-google-auth>=1.5.0 (from pandas-gbq)
  Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: psutil>=5.9.8 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from pandas-gbq) (7.0.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.15.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (2.31.0)
Requirement already satisfied: google-auth>=2.14.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (2.55.0)
Collecting google-auth-oauthlib>=0.7.0 (from pandas-gbq)
  Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.20.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas-gbq) (3.42.0)
Requirement already satisfied: packaging>=22.0.0 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from pandas-gbq) (25.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=5.29.6 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (7.35.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.24.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (1.28.0)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.34.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (49.0.0)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pandas>=1.5.3->pandas-gbq) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.0.0)
Requirement already satisfied: grpcio<2.0.0,>=1.41.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.81.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.41.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.81.1)
Requirement already satisfied: pyopenssl>=20.0.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (26.3.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.14.1->pandas-gbq) (0.6.3)
Requirement already satisfied: six>=1.5 in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2025.1.31)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: pycparser in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.21)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from grpcio<2.0.0,>=1.41.0->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (4.12.2)
Downloading pandas_gbq-0.35.0-py3-none-any.whl (50 kB)
Downloading db_dtypes-1.7.0-py3-none-any.whl (17 kB)
Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl (19 kB)
Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.3 MB ? eta -:--:--
    --------------------------------------- 0.5/27.3 MB 796.3 kB/s eta 0:00:34
    --------------------------------------- 0.5/27.3 MB 796.3 kB/s eta 0:00:34
    --------------------------------------- 0.5/27.3 MB 796.3 kB/s eta 0:00:34
    --------------------------------------- 0.5/27.3 MB 796.3 kB/s eta 0:00:34
   - -------------------------------------- 0.8/27.3 MB 457.2 kB/s eta 0:00:58
   - -------------------------------------- 0.8/27.3 MB 457.2 kB/s eta 0:00:58
   - -------------------------------------- 1.0/27.3 MB 510.8 kB/s eta 0:00:52
   - -------------------------------------- 1.3/27.3 MB 545.8 kB/s eta 0:00:48
   - -------------------------------------- 1.3/27.3 MB 545.8 kB/s eta 0:00:48
   -- ------------------------------------- 1.6/27.3 MB 576.7 kB/s eta 0:00:45
   -- ------------------------------------- 1.8/27.3 MB 601.3 kB/s eta 0:00:43
   -- ------------------------------------- 1.8/27.3 MB 601.3 kB/s eta 0:00:43
   -- ------------------------------------- 1.8/27.3 MB 601.3 kB/s eta 0:00:43
   -- ------------------------------------- 1.8/27.3 MB 601.3 kB/s eta 0:00:43
   --- ------------------------------------ 2.1/27.3 MB 543.6 kB/s eta 0:00:47
   --- ------------------------------------ 2.1/27.3 MB 543.6 kB/s eta 0:00:47
   --- ------------------------------------ 2.1/27.3 MB 543.6 kB/s eta 0:00:47
   --- ------------------------------------ 2.4/27.3 MB 512.8 kB/s eta 0:00:49
   --- ------------------------------------ 2.4/27.3 MB 512.8 kB/s eta 0:00:49

In [26]:
df = pd.read_sql("SELECT * FROM reviews", conn)

print(df.shape)
print(df.head())

(82, 5)
                                               title  \
0  Introducing a new rewards system for honest, i...
1          The Best Genmaicha Tea Brands of the Year
2                 First time drinking Rammstein Rum!
3                IKEA Stenkol Battery Charger Review
4                         Café Bustelo Coffee Review

                                                text  score  \
0  There are no incentives for consumers to write...     14
1  Genmaicha is a traditional Japanese tea that b...      3
2  [https://youtu.be/Qx2c7V6gUNA](https://youtu.b...      3
3  I have been using my Duracell CEF14 battery ch...      3
4                                                         2

                                              review  sentiment
0  Introducing a new rewards system for honest, i...          1
1  The Best Genmaicha Tea Brands of the Year Genm...          1
2  First time drinking Rammstein Rum! [https://yo...          1
3  IKEA Stenkol Battery Charger Review I have bee...          1
4                        Café Bustelo Coffee Review           1

In [27]:
print(df.columns)

Index(['title', 'text', 'score', 'review', 'sentiment'], dtype='str')

In [28]:
df["review"] = df["review"].fillna("")
df = df.dropna()

In [29]:
X = df["review"]
y = df["sentiment"]

In [31]:
!pip install scikit-learn

^C

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 671.5 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.2 MB 671.5 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/8.2 MB 716.8 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.2 MB 715.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.0/8.2 MB 715.9 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.2 MB 711.1 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.2 MB 711.1 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.2 MB 717.6 kB/s eta 0:00:10
   -------- ------------------------------- 1.8/8.2 MB 737.4 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.2 MB 737.4 kB/s eta 0:00:09
   ---------- ----------------------------- 2.1/8.2 MB 750.4 kB/s eta 0:00:09
   ----------- ---------------------------- 2.4/8.2 MB 743.7 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.2 MB 743.7 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.2 MB 752.8 kB/s eta 0:00:08
   -------------- ------------------------- 2.9/8.2 MB 759.1 kB/s eta 0:00:07
   -------------- ------------------------- 2.9/8.2 MB 759.1 kB/s eta 0:00:07
   --------------- ------------------------ 3.1/8.2 MB 751.1 kB/s eta 0:00:07
   --------------- ------------------------ 3.1/8.2 MB 751.1 kB/s eta 0:00:07
   ---------------- ----------------------- 3.4/8.2 MB 751.5 kB/s eta 0:00:07
   ---------------- ----------------------- 3.4/8.2 MB 751.5 kB/s eta 0:00:07
   ----------------- ---------------------- 3.7/8.2 MB 741.0 kB/s eta 0:00:07
   ------------------- -------------------- 3.9/8.2 MB 745.9 kB/s eta 0:00:06
   ------------------- -------------------- 3.9/8.2 MB 745.9 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.2 MB 750.9 kB/s eta 0:00:06
   --------------------- ------------------ 4.5/8.2 MB 752.9 kB/s eta 0:00:05
   --------------------- ------------------ 4.5/8.2 MB 752.9 kB/s eta 0:00:05
   ----------------------- ---------------- 4.7/8.2 MB 755.5 kB/s eta 0:00:05
   ------------------------ --------------- 5.0/8.2 MB 759.6 kB/s eta 0:00:05
   ------------------------ --------------- 5.0/8.2 MB 759.6 kB/s eta 0:00:05
   ------------------------- -------------- 5.2/8.2 MB 754.8 kB/s eta 0:00:04
   ------------------------- -------------- 5.2/8.2 MB 754.8 kB/s eta 0:00:04
   -------------------------- ------------- 5.5/8.2 MB 756.7 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.2 MB 759.2 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.2 MB 759.2 kB/s eta 0:00:04
   ----------------------------- ---------- 6.0/8.2 MB 761.5 kB/s eta 0:00:03
   ------------------------------ --------- 6.3/8.2 MB 762.4 kB/s eta 0:00:03
   ------------------------------ --------- 6.3/8.2 MB 762.4 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.2 MB 756.3 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.2 MB 756.3 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.2 MB 756.7 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.2 MB 756.7 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.2 MB 755.7 kB/s eta 0:00:02
   ----------------------------------- ---- 7.3/8.2 MB 756.2 kB/s eta 0:00:02
   ----------------------------------- ---- 7.3/8.2 MB 756.2 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.2 MB 757.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 757.9 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 757.9 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 756.7 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 751.9 kB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 812.6 kB/s eta 0:00:45
    --------------------------------------- 0.8/36.5 MB 829.5 kB/s eta 0:00:44
    --------------------------------------- 0.8/36.5 MB 829.5 kB/s eta 0:00:44
   - -------------------------------------- 1.0/36.5 MB 805.4 kB/s eta 0:00:45
   - -------------------------------------- 1.3/36.5 MB 810.6 kB/s eta 0:00:44
   - -------------------------------------- 1.3/36.5 MB 810.6 kB/s eta 0:00:44
   - -------------------------------------- 1.6/36.5 MB 816.3 kB/s eta 0:00:43
   -- ------------------------------------- 1.8/36.5 MB 796.9 kB/s eta 0:00:44
   -- ------------------------------------- 1.8/36.5 MB 796.9 kB/s eta 0:00:44
   -- ------------------------------------- 2.1/36.5 MB 790.0 kB/s eta 0:00:44
   -- ------------------------------------- 2.1/36.5 MB 790.0 kB/s eta 0:00:44
   -- ------------------------------------- 2.4/36.5 MB 782.9 kB/s eta 0:00:44
   -- ------------------------------------- 2.6/36.5 MB 786.1 kB/s eta 0:00:44
   -- ------------------------------------- 2.6/36.5 MB 786.1 kB/s eta 0:00:44
   --- ------------------------------------ 2.9/36.5 MB 790.0 kB/s eta 0:00:43
   --- ------------------------------------ 2.9/36.5 MB 790.0 kB/s eta 0:00:43
   --- ------------------------------------ 3.1/36.5 MB 788.2 kB/s eta 0:00:43
   --- ------------------------------------ 3.4/36.5 MB 791.7 kB/s eta 0:00:42
   --- ------------------------------------ 3.4/36.5 MB 791.7 kB/s eta 0:00:42
   ---- ----------------------------------- 3.7/36.5 MB 789.4 kB/s eta 0:00:42
   ---- ----------------------------------- 3.9/36.5 MB 792.0 kB/s eta 0:00:42
   ---- ----------------------------------- 3.9/36.5 MB 792.0 kB/s eta 0:00:42
   ---- ----------------------------------- 4.2/36.5 MB 797.3 kB/s eta 0:00:41
   ---- ----------------------------------- 4.5/36.5 MB 801.4 kB/s eta 0:00:40
   ---- ----------------------------------- 4.5/36.5 MB 801.4 kB/s eta 0:00:40
   ---- ----------------------------------- 4.5/36.5 MB 801.4 kB/s eta 0:00:40
   ----- ---------------------------------- 4.7/36.5 MB 776.1 kB/s eta 0:00:41
   ----- ---------------------------------- 5.0/36.5 MB 774.7 kB/s eta 0:00:41
   ----- ---------------------------------- 5.0/36.5 MB 774.7 kB/s eta 0:00:41
   ----- ---------------------------------- 5.2/36.5 MB 777.5 kB/s eta 0:00:41
   ------ --------------------------------- 5.5/36.5 MB 780.4 kB/s eta 0:00:40
   ------ --------------------------------- 5.5/36.5 MB 780.4 kB/s eta 0:00:40
   ------ --------------------------------- 5.8/36.5 MB 783.0 kB/s eta 0:00:40
   ------ --------------------------------- 6.0/36.5 MB 785.8 kB/s eta 0:00:39
   ------ --------------------------------- 6.0/36.5 MB 785.8 kB/s eta 0:00:39
   ------ --------------------------------- 6.3/36.5 MB 783.5 kB/s eta 0:00:39
   ------ --------------------------------- 6.3/36.5 MB 783.5 kB/s eta 0:00:39
   ------- -------------------------------- 6.6/36.5 MB 785.8 kB/s eta 0:00:39
   ------- -------------------------------- 6.8/36.5 MB 786.9 kB/s eta 0:00:38
   ------- -------------------------------- 6.8/36.5 MB 786.9 kB/s eta 0:00:38
   ------- -------------------------------- 7.1/36.5 MB 788.8 kB/s eta 0:00:38
   -------- ------------------------------- 7.3/36.5 MB 789.2 kB/s eta 0:00:37
   -------- ------------------------------- 7.3/36.5 MB 789.2 kB/s eta 0:00:37
   -------- ------------------------------- 7.6/36.5 MB 791.4 kB/s eta 0:00:37
   -------- ------------------------------- 7.6/36.5 MB 791.4 kB/s eta 0:00:37
   -------- ------------------------------- 7.6/36.5 MB 791.4 kB/s eta 0:00:37
   -------- ------------------------------- 7.6/36.5 MB 791.4 kB/s eta 0:00:37
   -------- ------------------------------- 7.6/36.5 MB 791.4 kB/s eta 0:00:37
   -------- ------------------------------- 7.9/36.5 MB 732.4 kB/s eta 0:00:40
   -------- ------------------------------- 8.1/36.5 MB 734.8 kB/s eta 0:00:39
   -------- ------------------------------- 8.1/36.5 MB 734.8 kB/s eta 0:00:39
   --------- ------------------------------ 8.4/36.5 MB 736.0 kB/s eta 0:00:39
   --------- ------------------------------ 8.7/36.5 MB 740.1 kB/s eta 0:00:38
   --------- ------------------------------ 8.7/36.5 MB 740.1 kB/s eta 0:00:38
   --------- ------------------------------ 8.7/36.5 MB 740.1 kB/s eta 0:00:38
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 724.7 kB/s eta 0:00:39
   ---------- ----------------------------- 9.2/36.5 MB 568.9 kB/s eta 0:00:49
   ---------- ----------------------------- 9.2/36.5 MB 568.9 kB/s eta 0:00:49
   ---------- ----------------------------- 9.2/36.5 MB 568.9 kB/s eta 0:00:49
   ---------- ----------------------------- 9.2/36.5 MB 568.9 kB/s eta 0:00:49
   ---------- ----------------------------- 9.2/36.5 MB 568.9 kB/s eta 0:00:49
   ---------- ----------------------------- 9.4/36.5 MB 549.4 kB/s eta 0:00:50
   ---------- ----------------------------- 9.4/36.5 MB 549.4 kB/s eta 0:00:50
   ---------- ----------------------------- 9.7/36.5 MB 553.5 kB/s eta 0:00:49
   ---------- ----------------------------- 10.0/36.5 MB 557.9 kB/s eta 0:00:48
   ---------- ----------------------------- 10.0/36.5 MB 557.9 kB/s eta 0:00:48
   ----------- ---------------------------- 10.2/36.5 MB 561.6 kB/s eta 0:00:47
   ----------- ---------------------------- 10.2/36.5 MB 561.6 kB/s eta 0:00:47
   ----------- ---------------------------- 10.5/36.5 MB 564.7 kB/s eta 0:00:47
   ----------- ---------------------------- 10.5/36.5 MB 564.7 kB/s eta 0:00:47
   ----------- ---------------------------- 10.7/36.5 MB 567.6 kB/s eta 0:00:46
   ------------ --------------------------- 11.0/36.5 MB 571.0 kB/s eta 0:00:45
   ------------ --------------------------- 11.0/36.5 MB 571.0 kB/s eta 0:00:45
   ------------ --------------------------- 11.3/36.5 MB 573.2 kB/s eta 0:00:45
   ------------ --------------------------- 11.3/36.5 MB 573.2 kB/s eta 0:00:45
   ------------ --------------------------- 11.5/36.5 MB 577.0 kB/s eta 0:00:44
   ------------ --------------------------- 11.5/36.5 MB 577.0 kB/s eta 0:00:44
   ------------ --------------------------- 11.8/36.5 MB 577.4 kB/s eta 0:00:43
   ------------ --------------------------- 11.8/36.5 MB 577.4 kB/s eta 0:00:43
   ------------- -------------------------- 12.1/36.5 MB 574.4 kB/s eta 0:00:43
   ------------- -------------------------- 12.1/36.5 MB 574.4 kB/s eta 0:00:43
   ------------- -------------------------- 12.1/36.5 MB 574.4 kB/s eta 0:00:43
   ------------- -------------------------- 12.3/36.5 MB 571.3 kB/s eta 0:00:43
   ------------- -------------------------- 12.3/36.5 MB 571.3 kB/s eta 0:00:43
   ------------- -------------------------- 12.6/36.5 MB 570.0 kB/s eta 0:00:42
   ------------- -------------------------- 12.6/36.5 MB 570.0 kB/s eta 0:00:42
   -------------- ------------------------- 12.8/36.5 MB 572.7 kB/s eta 0:00:42
   -------------- ------------------------- 12.8/36.5 MB 572.7 kB/s eta 0:00:42
   -------------- ------------------------- 13.1/36.5 MB 576.0 kB/s eta 0:00:41
   -------------- ------------------------- 13.1/36.5 MB 576.0 kB/s eta 0:00:41
   -------------- ------------------------- 13.4/36.5 MB 577.9 kB/s eta 0:00:41
   -------------- ------------------------- 13.6/36.5 MB 579.4 kB/s eta 0:00:40
   -------------- ------------------------- 13.6/36.5 MB 579.4 kB/s eta 0:00:40
   -------------- ------------------------- 13.6/36.5 MB 579.4 kB/s eta 0:00:40
   -------------- ------------------------- 13.6/36.5 MB 579.4 kB/s eta 0:00:40
   -------------- ------------------------- 13.6/36.5 MB 579.4 kB/s eta 0:00:40
   --------------- ------------------------ 13.9/36.5 MB 566.1 kB/s eta 0:00:40
   --------------- ------------------------ 13.9/36.5 MB 566.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.2/36.5 MB 568.1 kB/s eta 0:00:40
   --------------- ------------------------ 14.4/36.5 MB 549.9 kB/s eta 0:00:41
   --------------- ------------------------ 14.4/36.5 MB 549.9 kB/s eta 0:00:41
   --------------- ------------------------ 14.4/36.5 MB 549.9 kB/s eta 0:00:41
   --------------- ------------------------ 14.4/36.5 MB 549.9 kB/s eta 0:00:41
   --------------- ------------------------ 14.4/36.5 MB 549.9 kB/s eta 0:00:41
   ---------------- ----------------------- 14.7/36.5 MB 540.2 kB/s eta 0:00:41
   ---------------- ----------------------- 14.7/36.5 MB 540.2 kB/s eta 0:00:41
   ---------------- ----------------------- 14.7/36.5 MB 540.2 kB/s eta 0:00:41
   ---------------- ----------------------- 14.7/36.5 MB 540.2 kB/s eta 0:00:41
   ---------------- ----------------------- 14.9/36.5 MB 533.5 kB/s eta 0:00:41
   ---------------- ----------------------- 14.9/36.5 MB 533.5 kB/s eta 0:00:41
   ---------------- ----------------------- 14.9/36.5 MB 533.5 kB/s eta 0:00:41
   ---------------- ----------------------- 14.9/36.5 MB 533.5 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/36.5 MB 524.0 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/36.5 MB 524.0 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/36.5 MB 524.0 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/36.5 MB 524.0 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/36.5 MB 524.0 kB/s eta 0:00:41
   ---------------- ----------------------- 15.5/36.5 MB 515.4 kB/s eta 0:00:41
   ---------------- ----------------------- 15.5/36.5 MB 515.4 kB/s eta 0:00:41
   ---------------- ----------------------- 15.5/36.5 MB 515.4 kB/s eta 0:00:41
   ----------------- ---------------------- 15.7/36.5 MB 509.8 kB/s eta 0:00:41
   ----------------- ---------------------- 15.7/36.5 MB 509.8 kB/s eta 0:00:41
   ----------------- ---------------------- 15.7/36.5 MB 509.8 kB/s eta 0:00:41
   ----------------- ---------------------- 15.7/36.5 MB 509.8 kB/s eta 0:00:41
   ----------------- ---------------------- 15.7/36.5 MB 509.8 kB/s eta 0:00:41
   ----------------- ---------------------- 16.0/36.5 MB 492.4 kB/s eta 0:00:42
   ----------------- ---------------------- 16.0/36.5 MB 492.4 kB/s eta 0:00:42
   ----------------- ---------------------- 16.3/36.5 MB 490.9 kB/s eta 0:00:42
   ------------------ --------------------- 16.5/36.5 MB 491.2 kB/s eta 0:00:41
   ------------------ --------------------- 16.5/36.5 MB 491.2 kB/s eta 0:00:41
   ------------------ --------------------- 16.8/36.5 MB 491.3 kB/s eta 0:00:41
   ------------------ --------------------- 16.8/36.5 MB 491.3 kB/s eta 0:00:41
   ------------------ --------------------- 16.8/36.5 MB 491.3 kB/s eta 0:00:41
   ------------------ --------------------- 16.8/36.5 MB 491.3 kB/s eta 0:00:41
   ------------------ --------------------- 17.0/36.5 MB 475.1 kB/s eta 0:00:41
   ------------------ --------------------- 17.0/36.5 MB 475.1 kB/s eta 0:00:41
   ------------------ --------------------- 17.0/36.5 MB 475.1 kB/s eta 0:00:41
   ------------------ --------------------- 17.0/36.5 MB 475.1 kB/s eta 0:00:41
   ------------------ --------------------- 17.0/36.5 MB 475.1 kB/s eta 0:00:41
   ------------------ --------------------- 17.3/36.5 MB 456.2 kB/s eta 0:00:43
   ------------------ --------------------- 17.3/36.5 MB 456.2 kB/s eta 0:00:43
   ------------------ --------------------- 17.3/36.5 MB 456.2 kB/s eta 0:00:43
   ------------------- -------------------- 17.6/36.5 MB 448.4 kB/s eta 0:00:43
   ------------------- -------------------- 17.8/36.5 MB 447.7 kB/s eta 0:00:42
   ------------------- -------------------- 17.8/36.5 MB 447.7 kB/s eta 0:00:42
   ------------------- -------------------- 18.1/36.5 MB 450.4 kB/s eta 0:00:41
   ------------------- -------------------- 18.1/36.5 MB 450.4 kB/s eta 0:00:41
   -------------------- ------------------- 18.4/36.5 MB 450.3 kB/s eta 0:00:41
   -------------------- ------------------- 18.6/36.5 MB 449.4 kB/s eta 0:00:40
   -------------------- ------------------- 18.6/36.5 MB 449.4 kB/s eta 0:00:40
   -------------------- ------------------- 18.9/36.5 MB 447.7 kB/s eta 0:00:40
   -------------------- ------------------- 18.9/36.5 MB 447.7 kB/s eta 0:00:40
   -------------------- ------------------- 19.1/36.5 MB 446.9 kB/s eta 0:00:39
   -------------------- ------------------- 19.1/36.5 MB 446.9 kB/s eta 0:00:39
   --------------------- ------------------ 19.4/36.5 MB 446.2 kB/s eta 0:00:39
   --------------------- ------------------ 19.4/36.5 MB 446.2 kB/s eta 0:00:39
   --------------------- ------------------ 19.7/36.5 MB 446.5 kB/s eta 0:00:38
   --------------------- ------------------ 19.7/36.5 MB 446.5 kB/s eta 0:00:38
   --------------------- ------------------ 19.9/36.5 MB 440.4 kB/s eta 0:00:38
   ---------------------- ----------------- 20.2/36.5 MB 440.0 kB/s eta 0:00:38
   ---------------------- ----------------- 20.2/36.5 MB 440.0 kB/s eta 0:00:38
   ---------------------- ----------------- 20.2/36.5 MB 440.0 kB/s eta 0:00:38

In [32]:
import sklearn
print(sklearn.__version__)

1.9.0

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

ÉTAPE 1 — TF-IDF (vectorisation du texte)

Transformer le texte en chiffres (obligatoire pour ML)

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

2. Créer le vectorizer

In [36]:
vectorizer = TfidfVectorizer()

3. Apprendre + transformer le train set

In [37]:
X_train_vec = vectorizer.fit_transform(X_train)

In [ ]:
4. Transformer le test set

In [38]:
X_test_vec = vectorizer.transform(X_test)

5. Vérification

In [39]:
print(X_train_vec.shape)
print(X_test_vec.shape)

(65, 944)
(17, 944)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
model = LogisticRegression()

In [42]:
model.fit(X_train_vec, y_train)

LogisticRegression()

In [43]:
y_pred = model.predict(X_test_vec)

In [44]:
print(y_pred[:10])

[1 1 1 1 1 1 1 1 1 1]

In [45]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9411764705882353

In [46]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.94      1.00      0.97        16

    accuracy                           0.94        17
   macro avg       0.47      0.50      0.48        17
weighted avg       0.89      0.94      0.91        17

c:\Users\sh_mi\anaconda3\envs\notebook\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sh_mi\anaconda3\envs\notebook\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sh_mi\anaconda3\envs\notebook\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [58]:
import joblib

joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import joblib

# données exemple
texts = ["j'aime ce produit", "je déteste ce produit"]
labels = [1, 0]

# vectorisation
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

# modèle
model = LogisticRegression()
model.fit(X, labels)

# sauvegarde
joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("Modèle et vectorizer sauvegardés !")

Modèle et vectorizer sauvegardés !

In [60]:
print(model)
print(vectorizer)

LogisticRegression()
TfidfVectorizer()

In [61]:
import joblib

joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [63]:
import joblib

joblib.dump(model, "model.pkl")

['model.pkl']

In [62]:
import os

print(os.getcwd())

c:\Users\sh_mi\AppData\Local\Programs\Microsoft VS Code

In [49]:
loaded_model = joblib.load("model.pkl")
loaded_vectorizer = joblib.load("vectorizer.pkl")

text = ["this product is very bad"]

vec = loaded_vectorizer.transform(text)
print(loaded_model.predict(vec))

[1]

In [50]:
!pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.137.1-py3-none-any.whl.metadata (26 kB)
Collecting uvicorn
  Downloading uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Collecting starlette>=0.46.0 (from fastapi)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting pydantic>=2.9.0 (from fastapi)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (4.12.2)
Collecting typing-inspection>=0.4.2 (from fastapi)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting click>=7.0 (from uvicorn)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: h11>=0.8 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from uvicorn) (0.14.0)
Requirement already satisfied: colorama in c:\users\sh_mi\appdata\roaming\python\python313\site-packages (from click>=7.0->uvicorn) (0.4.6)
Collecting annotated-types>=0.6.0 (from pydantic>=2.9.0->fastapi)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic>=2.9.0->fastapi)
  Downloading pydantic_core-2.46.4-cp313-cp313-win_amd64.whl.metadata (6.7 kB)
Collecting typing-extensions>=4.8.0 (from fastapi)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from starlette>=0.46.0->fastapi) (4.7.0)
Requirement already satisfied: idna>=2.8 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)
Downloading fastapi-0.137.1-py3-none-any.whl (121 kB)
Downloading uvicorn-0.49.0-py3-none-any.whl (71 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 844.5 kB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 844.5 kB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 844.5 kB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 844.5 kB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 844.5 kB/s eta 0:00:02
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 400.7 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 262.8 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 193.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 193.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 193.7 kB/s eta 0:00:04
   ------------------------- -------------- 1.3/2.1 MB 193.7 kB/s eta 0:00:04
   ------------------------------ --------- 1.6/2.1 MB 207.9 kB/s eta 0:00:03
   ------------------------------ --------- 1.6/2.1 MB 207.9 kB/s eta 0:00:03
   ----------------------------------- ---- 1.8/2.1 MB 235.2 kB/s eta 0:00:02
   ----------------------------------- ---- 1.8/2.1 MB 235.2 kB/s eta 0:00:02
   ---------------------------------------- 2.1/2.1 MB 256.7 kB/s eta 0:00:00
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Installing collected packages: typing-extensions, click, annotated-types, annotated-doc, uvicorn, typing-inspection, starlette, pydantic-core, pydantic, fastapi
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
Successfully installed annotated-doc-0.0.4 annotated-types-0.7.0 click-8.4.1 fastapi-0.137.1 pydantic-2.13.4 pydantic-core-2.46.4 starlette-1.3.1 typing-extensions-4.15.0 typing-inspection-0.4.2 uvicorn-0.49.0

fichier : main.py

In [56]:
!pip install fastapi
import fastapi

Requirement already satisfied: fastapi in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (0.137.1)
Requirement already satisfied: starlette>=0.46.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from fastapi) (0.0.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from starlette>=0.46.0->fastapi) (4.7.0)
Requirement already satisfied: idna>=2.8 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\sh_mi\anaconda3\envs\notebook\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)

In [51]:
from fastapi import FastAPI
import joblib

app = FastAPI()

model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

Endpoint prediction

In [52]:
@app.post("/predict")
def predict(text: str):
    vec = vectorizer.transform([text])
    pred = model.predict(vec)

    sentiment = "positif" if pred[0] == 1 else "negatif"

    return {"sentiment": sentiment}

Lancer

In [53]:
print("MAIN FILE LOADED")

MAIN FILE LOADED

In [57]:
import joblib

model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import joblib

# mini dataset
texts = [
    "j'aime ce produit",
    "je déteste ce produit",
    "c'est super",
    "c'est nul"
]

labels = [1, 0, 1, 0]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

model = LogisticRegression()
model.fit(X, labels)

joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("OK modèles recréés")

OK modèles recréés